// Wraps the real content.js so it can run in a plain page: stubs chrome.runtime (which does not
// exist outside an extension) and exposes __arm(). Nothing about the capture logic is modified —
// the point of the harness is that the file under test is byte-for-byte the shipped one.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, "..", "content.js"), "utf8");

const shim = `// GENERATED by build-harness.mjs — do not edit.
// window.chrome exists in every Chrome page but carries no \`runtime\` outside an extension,
// so this replaces it outright rather than falling back with \`||\`.
window.chrome = {
  runtime: {
    sendMessage: (m) => { if (m && m.__clipxd && window.__collect) window.__collect(m.evt); },
    onMessage: { _l: [], addListener(fn) { this._l.push(fn); } },
  },
};
`;
const tail = `
window.__arm = () => chrome.runtime.onMessage._l.forEach((fn) => fn({ cmd: "arm" }));
`;
writeFileSync(join(here, "content-under-test.js"), shim + src + tail);
console.log("built extension/test/content-under-test.js from the real content.js");
